version: "3.8"
services:
    php:
        build: docker/php/.
        container_name: app-php
        working_dir: /home/www/
        volumes:
            - ./:/home/www/
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: "serverName=localhost"

    nginx:
        image: nginx:alpine
        container_name: app-nginx
        working_dir: /home/www/
        ports:
            - "80:80"
        volumes:
            - ./:/home/www/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

    mysql:
        image: mysql:5.7.22
        container_name: app-mysql
        restart: always
        environment:
            - MYSQL_DATABASE=dev
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - "8982:3306"